### ISSUE TITLE
Game isn't loading after setting up

### ISSUE THREAD

**Issue by japalmn** [benletchford/stratego.io#30]
Hi—my friend and I use your Stratego game often, thank you. We went on to play tonight and for both of us, it just says "Creating game" and the wheel is spinning forever. We just played a few days ago and it was working. Do you know what's going on? Thank you!

**Comment by beatofftwitcher** [comment]
Apparently the developer doesn't care.

**Comment by benletchford** [comment]
Fixed now - sorry for inconvenience.
